version: '3.8'
services:
  penpot-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    volumes:
    - ../volumes/postgres:/var/lib/postgresql/data:Z,U
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
  penpot-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command:
    - redis-server
    - --requirepass
    - ${REDIS_PASSWORD}
    volumes:
    - ../volumes/redis:/data:Z,U
    healthcheck:
      test:
      - CMD
      - redis-cli
      - -a
      - ${REDIS_PASSWORD}
      - ping
      interval: 10s
      timeout: 5s
      retries: 5
  penpot-backend:
    image: penpotapp/backend:latest
    restart: unless-stopped
    depends_on:
      penpot-postgres:
        condition: service_healthy
      penpot-redis:
        condition: service_healthy
    environment:
      PENPOT_DATABASE_USERNAME: ${POSTGRES_USER}
      PENPOT_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      PENPOT_PUBLIC_URI: ${PENPOT_PUBLIC_URI}
      PENPOT_DATABASE_URI: postgresql://penpot-postgres:5432/${POSTGRES_DB}
      PENPOT_REDIS_URI: redis://default:${REDIS_PASSWORD}@penpot-redis:6379/0
      PENPOT_TELEMETRY_ENABLED: ${PENPOT_TELEMETRY_ENABLED}
      PENPOT_SMTP_ENABLED: ${SMTP_ENABLED}
      PENPOT_SMTP_DEFAULT_FROM: ${SMTP_DEFAULT_FROM}
      PENPOT_SMTP_HOST: ${SMTP_HOST}
      PENPOT_SMTP_PORT: ${SMTP_PORT}
      PENPOT_SMTP_USERNAME: ${SMTP_USERNAME}
      PENPOT_SMTP_PASSWORD: ${SMTP_PASSWORD}
      PENPOT_SMTP_TLS: ${SMTP_TLS}
    volumes:
    - ../volumes/assets:/opt/data:Z,U
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:6060/health
      interval: 10s
      timeout: 5s
      retries: 10
  penpot-exporter:
    image: penpotapp/exporter:latest
    restart: unless-stopped
    depends_on:
      penpot-backend:
        condition: service_started
      penpot-redis:
        condition: service_started
    environment:
      PENPOT_PUBLIC_URI: ${PENPOT_PUBLIC_URI}
      PENPOT_BACKEND_URI: http://penpot-backend:6060
      PENPOT_REDIS_URI: redis://default:${REDIS_PASSWORD}@penpot-redis:6379/0
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:6061/health
      interval: 10s
      timeout: 5s
      retries: 10
  penpot-frontend:
    image: penpotapp/frontend:latest
    restart: unless-stopped
    depends_on:
      penpot-backend:
        condition: service_started
      penpot-exporter:
        condition: service_started
    environment:
      PENPOT_PUBLIC_URI: ${PENPOT_PUBLIC_URI}
      PENPOT_BACKEND_URI: http://penpot-backend:6060
      PENPOT_EXPORTER_URI: http://penpot-exporter:6061
    ports:
    - ${HOST_PENPOT_PORT}:8080
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080
      interval: 10s
      timeout: 5s
      retries: 10
networks:
  default:
    name: penpot-net
